changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions[bot]
      - dependabot[bot]
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
        - semver-major
    - title: Features
      labels:
        - enhancement
        - feature
        - feat
    - title: Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: Maintenance
      labels:
        - chore
        - refactor
        - ci
        - dependencies
    - title: Other changes
      labels:
        - "*"
